### ISSUE TITLE
TypeError: Expected Buffer

### ISSUE THREAD

**Issue by mttbrt** [radixdlt/radixdlt-js-server-example#3]
Hello, when I run the server (`node server`) after installing all required dependencies (`npm install`) I get this error:  
```
/home/methk/Downloads/radixdlt-js-server-example-master/node_modules/base-x/src/index.js:24
    if (!_Buffer.isBuffer(source)) { throw new TypeError('Expected Buffer') }
                                     ^

TypeError: Expected Buffer
    at Object.encode (/home/methk/Downloads/radixdlt-js-server-example-master/node_modules/base-x/src/index.js:24:44)
    at RadixKeyPair.getAddress (/home/methk/Downloads/radixdlt-js-server-example-master/node_modules/radixdlt/build/main/modules/wallet/RadixKeyPair.js:67:31)
    at RadixIdentityManager.generateSimpleIdentity (/home/methk/Downloads/radixdlt-js-server-example-master/node_modules/radixdlt/build/main/modules/identity/RadixIdentityManager.js:14:37)
    at Object.<anonymous> (/home/methk/Downloads/radixdlt-js-server-example-master/src/server.js:13:35)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11

```

I'm currently using:
* NPM version: 6.12.0
* Node version: v12.10.0

Thanks for helping.

**Comment by mttbrt** [comment]
I solved the problem converting the `addressBytes` array in RadixKeyPair.js to a Buffer object:

In module `radixdlt` (`radixdlt/build/main/modules/wallet/RadixKeyPair.js`) change line 67 from:
```
return bs58_1.default.encode(addressBytes);
```
to:
```
return bs58_1.default.encode(Buffer.from(addressBytes));
```
